---
title: "Exploratory Data Analysis of Alerts Dataset"
author: "Daniel P. Riggins"
date: "6/5/2021"
output: html_document
---

```{r}
library(tidyverse)
library(lubridate)
library(DataExplorer)
```

```{r}
# Attribution: https://stackoverflow.com/a/39894310/3511838

get_season <- function(input.date){
  numeric.date <- 100*month(input.date)+day(input.date)
  ## input Seasons upper limits in the form MMDD in the "break =" option:
  cuts <- base::cut(numeric.date, breaks = c(0,0319,0620,0921,1220,1231)) 
  # rename the resulting groups (could've been done within cut(...levels=) if "Winter" wasn't double
  levels(cuts) <- c("Winter","Spring","Summer","Fall","Winter")
  return(cuts)
}
```


```{r}
alerts_raw <- read_csv("data/alerts.csv")

alerts$registration <- dmy_hms(alerts$registration)

alerts <- alerts_raw %>%
    mutate(
        year = year(registration),
        month = month(registration),
        season = get_season(registration),
        day_of_month = day(registration),
        day_of_week = lubridate::wday(registration, label = TRUE),
        on_weekday = if_else(
            condition = (day_of_week > "Sun" & day_of_week < "Sat"),
            TRUE,
            FALSE
        ),
        hour = hour(registration),
        during_business_hours = if_else(
            condition = (hour > 7 & hour < 16),
            TRUE,
            FALSE
        ),
        easily_reachable = if_else(
            condition = (on_weekday == TRUE & during_business_hours == TRUE),
            TRUE,
            FALSE
        )
    )

glimpse(alerts)
```

```{r}
#create_report(alerts)
```

```{r}
alerts %>% 
    ggplot(aes(x = age)) +
    geom_bar()
```

```{r}
alerts %>% ggplot(aes(x = day_of_month)) +
    geom_bar()
```

```{r}
alerts %>% ggplot(aes(x = hour)) +
    geom_bar()
```

```{r}
total_alerts_by_client <- alerts %>% 
    group_by(nonderived_id) %>%
    summarize(total_alerts = max(totalerts_n)) %>%
    ungroup()

total_alerts_by_client %>%
    ggplot(aes(x = total_alerts)) +
    geom_bar()
```

```{r}
total_alerts_by_client %>%
    summarise(
        total_clients = n(),
        mean_total_alerts = mean(total_alerts),
        median_total_alerts = median(total_alerts)
    )
```

```{r}
alerts %>%
    select(
        season,
        location,
        easily_reachable
    ) %>%
    plot_bar(by = "easily_reachable")
```

